###########################################################
# ReIDer config:
###########################################################
# --- # Facenet
# ri_name: Facenet
# gpu_mem: 0.585
# model_det: ri_facenet/models/det
# model_file: ri_facenet/models/20180402-114759/20180402-114759.pb
# classifier_file: ri_facenet/classifier/gta5.pkl
# batch_size: 1000
# min_confidence: 0.75
# yl_h_callibration: [-125, 75]
# yl_w_callibration: [-55, 55]
# op_h_callibration: [-85, 25]
# op_w_callibration: [-35, 35]
###########################################################
# --- # DeepReID
# ri_name: DeepReID
# classes_txt: ri_deepreid/classifier/gta5.txt
# classifier_pkl: ri_deepreid/classifier/gta5_osnet_ain_ms_d_c.pkl
# train_data: ri_deepreid/data
# model_name: osnet_ain_x1_0
# model_path: ri_deepreid/pretrained/torchreid/osnet_ain_ms_d_c.pth.tar
# min_confidence: 0.35
###########################################################
ri_name: Facenet
gpu_mem: 0.585
model_det: ri_facenet/models/det
model_file: ri_facenet/models/20180402-114759/20180402-114759.pb
classifier_file: ri_facenet/classifier/gta5.pkl
batch_size: 1000
min_confidence: 0.75
yl_h_callibration: [-125, 75]
yl_w_callibration: [-55, 55]
op_h_callibration: [-85, 25]
op_w_callibration: [-35, 35]
---
ri_name: DeepReID
classes_txt: ri_deepreid/classifier/gta5.txt
classifier_pkl: ri_deepreid/classifier/gta5_osnet_ain_ms_d_c.pkl
train_data: ri_deepreid/data
model_name: osnet_ain_x1_0
model_path: ri_deepreid/pretrained/torchreid/osnet_ain_ms_d_c.pth.tar
min_confidence: 0.35
