name: Build PyPI
on:
  push:
    tags:
      - "v*"
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools>=67.2.0"
        pip install wheel build
    - name: Build .tar.gz
      run: |
        python -m build --sdist --skip-dependency-check
    - name: Build .whl
      run: |
        python -m build --wheel --skip-dependency-check
    - name: Publish 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Archive all
      uses: actions/upload-artifact@v3
      with:
        name: dist-all
        path: |
          dist
          !dist/**/*.md
