name: Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
permissions:
    contents: write
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install base requirements
      run: |
        cd requirements
        python -m pip install --upgrade pip
        pip install "setuptools>=67.2.0"
        pip install wheel build
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        pip install sphinx myst-parser pydata-sphinx-theme readthedocs-sphinx-search
        pip install --upgrade sphinx
        pip freeze
    - name: Sphinx build
      run: |
        sphinx-build docs _build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
